sudo: false
language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
  - docker run -p 5432:5432 -e POSTGRES_USER=test -e POSTGRES_PASSWORD=123456 -d postgres:alpine
script:
  - npm test

after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
